name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements/dev.txt

    - name: Run Black
      run: |
          source .venv/bin/activate
          black --skip-string-normalization .

    - name: Run Pylint
      run: |
          source .venv/bin/activate
          ./.venv/bin/pylint . --ignore=.venv --disable=too-few-public-methods

    - name: Validate OpenAPI Spec
      run: |
          source .venv/bin/activate
          openapi-spec-validator openapi.json
